### PR TITLE
Add string encryption pass

### PR DESCRIPTION
**Pull request by yag00**
fully functional string encryption pass

### CODE REVIEW

**Comment by yag00** [comment]
Try my recent new changes ( commit 8f72e04 ). //cc @mbazaliy 
The string encryption now handle a lot more cases. If you find some case that did not work send me a test case, i'll work on it...

**Comment by mbazaliy** [comment]
I will test your changes today. llvm 3.4 only ?

**Comment by yag00** [comment]
Yes LLVM 3.4 only i did not port To LLVM 3.5 yet ...

**Comment by yag00** [comment]
Try the last commit on my branch ... Let me know ...

**Comment by mbazaliy** [comment]
Looks good on llvm 3.4, as I see objc string literals and NSString formats are skipped from encryption

**Pull request closed without merging**
